"""
Centralized configuration for all 4 paper trading bots.
"""

TOTAL_CAPITAL = 2300.0

BOT_CONFIGS = {
    "poly": {
        "name": "Polymarket AI",
        "script": "polymarket_real.py",
        "capital": 800.0,
        "state_file": "poly_state.json",
        "log_file": "poly_log.json",
        "equity_file": "poly_equity.json",
        "heartbeat_file": "heartbeat_poly.json",
        "cycle_seconds": 300,
        "color": "#8b5cf6",
    },
    "narrative": {
        "name": "Narrative Rotation",
        "script": "narrative_v2.py",
        "capital": 600.0,
        "state_file": "narrative_state.json",
        "log_file": "narrative_log.json",
        "equity_file": "narrative_equity.json",
        "heartbeat_file": "heartbeat_narrative.json",
        "cycle_seconds": 120,
        "color": "#06b6d4",
    },
    "smartmoney": {
        "name": "Smart Money Tracker",
        "script": "smartmoney_v2.py",
        "capital": 400.0,
        "state_file": "smartmoney_state.json",
        "log_file": "smartmoney_log.json",
        "equity_file": "smartmoney_equity.json",
        "heartbeat_file": "heartbeat_smartmoney.json",
        "cycle_seconds": 600,
        "color": "#10b981",
    },
    "airdrop": {
        "name": "Airdrop Tracker",
        "script": "airdrop_bot.py",
        "capital": 200.0,
        "state_file": "airdrop_state.json",
        "log_file": "airdrop_log.json",
        "equity_file": "airdrop_equity.json",
        "heartbeat_file": "heartbeat_airdrop.json",
        "cycle_seconds": 120,
        "color": "#f59e0b",
    },
    "sentiment": {
        "name": "Sentiment DeepSeek",
        "script": "sentiment_bot.py",
        "capital": 500.0,
        "state_file": "sentiment_state.json",
        "log_file": "sentiment_log.json",
        "equity_file": "sentiment_equity.json",
        "heartbeat_file": "heartbeat_sentiment.json",
        "cycle_seconds": 300,
        "color": "#ec4899",
    },
    "sentiment_v2": {
        "name": "Sentiment V2 Wide",
        "script": "sentiment_v2_bot.py",
        "capital": 500.0,
        "state_file": "sentiment_v2_state.json",
        "log_file": "sentiment_v2_log.json",
        "equity_file": "sentiment_v2_equity.json",
        "heartbeat_file": "heartbeat_sentiment_v2.json",
        "cycle_seconds": 300,
        "color": "#8b5cf6",
    },
    "sentiment_v3": {
        "name": "Sentiment V3 Ultra",
        "script": "sentiment_v3_bot.py",
        "capital": 500.0,
        "state_file": "sentiment_v3_state.json",
        "log_file": "sentiment_v3_log.json",
        "equity_file": "sentiment_v3_equity.json",
        "heartbeat_file": "heartbeat_sentiment_v3.json",
        "cycle_seconds": 300,
        "color": "#f59e0b",
    },
    "grid": {
        "name": "Grid Trading",
        "script": "grid_bot.py",
        "capital": 400.0,
        "state_file": "grid_state.json",
        "log_file": "grid_log.json",
        "equity_file": "grid_equity.json",
        "heartbeat_file": "heartbeat_grid.json",
        "cycle_seconds": 120,
        "color": "#06b6d4",
    },
    "poly5min": {
        "name": "Poly5Min Momentum",
        "script": "poly5min_bot.py",
        "capital": 300.0,
        "state_file": "poly5min_state.json",
        "log_file": "poly5min_log.json",
        "equity_file": "poly5min_equity.json",
        "heartbeat_file": "heartbeat_poly5min.json",
        "cycle_seconds": 300,
        "color": "#f59e0b",
    },
    "autoresearch": {
        "name": "AutoResearch Dual-Regime",
        "script": "autoresearch_bot.py",
        "capital": 500.0,
        "state_file": "autoresearch_state.json",
        "log_file": "autoresearch_log.json",
        "equity_file": "autoresearch_equity.json",
        "heartbeat_file": "heartbeat_autoresearch.json",
        "cycle_seconds": 1800,
        "color": "#10b981",
    },
    "sentiment_ls_v2": {
        "name": "Sentiment LS V2",
        "script": "sentiment_ls_v2.py",
        "capital": 500.0,
        "state_file": "sentiment_ls_v2_state.json",
        "log_file": "sentiment_ls_v2_log.json",
        "equity_file": "sentiment_ls_v2_equity.json",
        "heartbeat_file": "heartbeat_sentiment_ls_v2.json",
        "cycle_seconds": 300,
        "color": "#f97316",
    },
    "sentiment_ls_v3": {
        "name": "Sentiment LS V3",
        "script": "sentiment_ls_v3.py",
        "capital": 200.0,
        "state_file": "sentiment_ls_v3_state.json",
        "log_file": "sentiment_ls_v3_log.json",
        "equity_file": "sentiment_ls_v3_equity.json",
        "heartbeat_file": "heartbeat_sentiment_ls_v3.json",
        "cycle_seconds": 300,
        "color": "#eab308",
    },
    # === FLEET ZAID — capital TOTAL $1000 reparti egalement ===
    "sentiment_ls_v3_lo": {
        "name": "LS V3 LO",
        "script": "sentiment_ls_v3_lo.py",
        "capital": 200.0,
        "state_file": "sentiment_ls_v3_lo_state.json",
        "log_file": "sentiment_ls_v3_lo_log.json",
        "equity_file": "sentiment_ls_v3_lo_equity.json",
        "heartbeat_file": "heartbeat_sentiment_ls_v3_lo.json",
        "cycle_seconds": 300,
        "color": "#22d3ee",
    },
    "confluence_reverse": {
        "name": "Confluence Reverse",
        "script": "confluence_reverse.py",
        "capital": 200.0,
        "state_file": "confluence_reverse_state.json",
        "log_file": "confluence_reverse_log.json",
        "equity_file": "confluence_reverse_equity.json",
        "heartbeat_file": "heartbeat_confluence_reverse.json",
        "cycle_seconds": 180,
        "color": "#16a34a",
    },
    "ultimate_v2_reverse": {
        "name": "Ultimate V2 Reverse",
        "script": "ultimate_v2_reverse.py",
        "capital": 200.0,
        "state_file": "ultimate_v2_reverse_state.json",
        "log_file": "ultimate_v2_reverse_log.json",
        "equity_file": "ultimate_v2_reverse_equity.json",
        "heartbeat_file": "heartbeat_ultimate_v2_reverse.json",
        "cycle_seconds": 600,
        "color": "#8b5cf6",
    },
    "twitter_ls": {
        "name": "Twitter LS Scraper",
        "script": "twitter_ls_bot.py",
        "capital": 10000.0,
        "state_file": "twitter_ls_state.json",
        "log_file": "twitter_ls_log.json",
        "equity_file": "twitter_ls_equity.json",
        "heartbeat_file": "heartbeat_twitter_ls.json",
        "cycle_seconds": 120,
        "color": "#1d9bf0",
    },
    "trending_ls": {
        "name": "Trending LS VADER",
        "script": "trending_ls_bot.py",
        "capital": 10000.0,
        "state_file": "trending_ls_state.json",
        "log_file": "trending_ls_log.json",
        "equity_file": "trending_ls_equity.json",
        "heartbeat_file": "heartbeat_trending_ls.json",
        "cycle_seconds": 120,
        "color": "#10b981",
    },
    "social_ls": {
        "name": "Social LS Reddit",
        "script": "social_ls_bot.py",
        "capital": 10000.0,
        "state_file": "social_ls_state.json",
        "log_file": "social_ls_log.json",
        "equity_file": "social_ls_equity.json",
        "heartbeat_file": "heartbeat_social_ls.json",
        "cycle_seconds": 120,
        "color": "#3b82f6",
    },
    "ultimate_v2": {
        "name": "Ultimate V2 FullExpo",
        "script": "ultimate_v2_bot.py",
        "capital": 10000.0,
        "state_file": "ultimate_v2_state.json",
        "log_file": "ultimate_v2_log.json",
        "equity_file": "ultimate_v2_equity.json",
        "heartbeat_file": "heartbeat_ultimate_v2.json",
        "cycle_seconds": 120,
        "color": "#ef4444",
    },
    # ─── TP VARIANTS (Progressive Take-Profit) ───
    "sentiment_ls_v2_tp": {
        "name": "Sentiment LS V2 TP",
        "script": "sentiment_ls_v2_tp.py",
        "capital": 10000.0,
        "state_file": "sentiment_ls_v2_tp_state.json",
        "log_file": "sentiment_ls_v2_tp_log.json",
        "equity_file": "sentiment_ls_v2_tp_equity.json",
        "heartbeat_file": "heartbeat_sentiment_ls_v2_tp.json",
        "cycle_seconds": 120,
        "color": "#ea580c",
    },
    "sentiment_ls_v3_tp": {
        "name": "Sentiment LS V3 TP",
        "script": "sentiment_ls_v3_tp.py",
        "capital": 200.0,
        "state_file": "sentiment_ls_v3_tp_state.json",
        "log_file": "sentiment_ls_v3_tp_log.json",
        "equity_file": "sentiment_ls_v3_tp_equity.json",
        "heartbeat_file": "heartbeat_sentiment_ls_v3_tp.json",
        "cycle_seconds": 120,
        "color": "#ca8a04",
    },
    "social_ls_tp": {
        "name": "Social LS TP",
        "script": "social_ls_tp.py",
        "capital": 10000.0,
        "state_file": "social_ls_tp_state.json",
        "log_file": "social_ls_tp_log.json",
        "equity_file": "social_ls_tp_equity.json",
        "heartbeat_file": "heartbeat_social_ls_tp.json",
        "cycle_seconds": 120,
        "color": "#0891b2",
    },
    "ultimate_tp": {
        "name": "Ultimate TP",
        "script": "ultimate_tp.py",
        "capital": 10000.0,
        "state_file": "ultimate_tp_state.json",
        "log_file": "ultimate_tp_log.json",
        "equity_file": "ultimate_tp_equity.json",
        "heartbeat_file": "heartbeat_ultimate_tp.json",
        "cycle_seconds": 120,
        "color": "#d97706",
    },
    "ultimate_v2_tp": {
        "name": "Ultimate V2 TP",
        "script": "ultimate_v2_tp.py",
        "capital": 10000.0,
        "state_file": "ultimate_v2_tp_state.json",
        "log_file": "ultimate_v2_tp_log.json",
        "equity_file": "ultimate_v2_tp_equity.json",
        "heartbeat_file": "heartbeat_ultimate_v2_tp.json",
        "cycle_seconds": 120,
        "color": "#7c3aed",
    },
    "confluence": {
        "name": "Confluence Bot",
        "script": "confluence_bot.py",
        "capital": 10000.0,
        "state_file": "confluence_state.json",
        "log_file": "confluence_log.json",
        "equity_file": "confluence_equity.json",
        "heartbeat_file": "heartbeat_confluence.json",
        "cycle_seconds": 120,
        "color": "#16a34a",
    },
    "confluence_tp": {
        "name": "Confluence TP Bot",
        "script": "confluence_tp_bot.py",
        "capital": 10000.0,
        "state_file": "confluence_tp_state.json",
        "log_file": "confluence_tp_log.json",
        "equity_file": "confluence_tp_equity.json",
        "heartbeat_file": "heartbeat_confluence_tp.json",
        "cycle_seconds": 120,
        "color": "#059669",
    },
}

TELEGRAM_TOKEN = "8685866733:AAEhP42Qc5i-_Yw5MOfYwuXRmqOpbphILhg"
TELEGRAM_CHAT = "5047076645"

SLIPPAGE_BPS = 10
FEE_BPS = 10
MAX_LOG_ENTRIES = 500
MAX_EQUITY_POINTS = 2880